package com.example.artifacthunter.models;

public enum Status {
    PLAYER_VISITED,
    ARTIFACT_NOT_VISITED,
    DANGEROUS_NOT_VISITED,
    DANGEROUS_NOT_VISITED_MARKED,
    NOT_VISITED_MARKED,
    VISITED,
    NOT_VISITED,
    PLAYER_ARTIFACT,
    PLAYER_DANGEROUS,
    DANGEROUS_VISITED,
    ARTIFACT_NOT_VISITED_MARKED
}
